# Generated by Django 5.2.4 on 2025-07-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
