# Generated by Django 5.2.4 on 2025-07-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_cliente', '0002_cliente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(blank=True, max_length=14, null=True)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
    ]
