# Generated by Django 5.2.4 on 2025-07-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_cliente', '0003_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
